---
title: "PA1_template.Rmd"
output: html_document
---


## Peer-graded Assignment: Course Project 1


### Loading and preprocessing the data

```{r}
data <- read.csv(file = "activity.csv", header = TRUE)
```

### What is mean total number of steps taken per day?

```{r}
#Remove NAs from data:
processed_data <- data[complete.cases(data),] 

#Format dates to date format
processed_data$date <- as.Date(processed_data$date)

#Create new dataset with the sum of steps per day
sum_steps <- aggregate(processed_data["steps"], by = processed_data["date"], sum)

#Create Histogram of Number of Steps per day
hist(sum_steps$steps, col = "blue", main = "Total Number of Steps per day", breaks = 10, 
     xlab = "Number of Steps", ylab = "Frequency")

#Calculate Mean and Median
mean <- mean(sum_steps$steps)
median <- median(sum_steps$steps)
```

The mean is `r mean`.
The median is `r median`.

### What is the average daily activity pattern?

``` {r}
#Create new dataset with the mean average steps per interval
avg_steps <- aggregate(steps ~ interval, data = data, mean, na.rm = TRUE)

#Create Time Series Plot
plot(steps ~ interval, data = avg_steps, type = "l", col = "blue", xlab = "Interval", ylab = "Number of Steps")

#Check Maximum number of steps and which interval
max_steps <- max(avg_steps$steps)
max_interval <- subset(avg_steps, steps == max_steps)
```

The Maximum Number of steps is `r max_steps`.
The Maximum Number of steps happened on the `r max_interval$interval` interval.